parameters:
#    cene_pandautilities.example.class: Cene\CenePandaUtilitiesBundle\Example

services:
#    cene_pandautilities.example:
#        class: %cene_pandautilities.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
